### ISSUE TITLE
disableScroll = true && scrollTo = true combo does not work

### ISSUE THREAD

**Issue by rwwagner90** [rwwagner90/ember-shepherd#35]
Currently, if you set both to true, it disables scroll which breaks scrollTo. Need to work around this.

**Comment by craigsketchley** [comment]
Yes, I was actually just going to mention this. I noticed in Shepherd they have an undocumented [`scrollToHandler`](https://github.com/HubSpot/shepherd/blob/master/src/js/shepherd.js#L290) option for a step, otherwise they just call `elem.scrollIntoView()`.

I was thinking we could implement a `scrollToHandler` where we essentially wrap a `elem.scrollIntoView()` with calls to enable/disable scrollbar scrolling (using the [example given](https://github.com/ultrapasty/jquery-disablescroll#example-usage) in the `jquery-disablescroll`).

**Comment by rwwagner90** [comment]
@craigsketchley that sounds logical to me. Would you be interested in working on that functionality or would you like me to do it? I'm fine with either way.

**Comment by craigsketchley** [comment]
I'll give it a go.

**Comment by rwwagner90** [comment]
Sounds good. Let me know if you need any help or decide you want me to do it instead. Do you have an email you want listed in the collaborators? I didn't see one in your GitHub profile.

**Comment by craigsketchley** [comment]
Sure, will do :) my email's craigsketchley@gmail.com. I'll get a PR up for this today.

**Comment by rwwagner90** [comment]
@craigsketchley how's your progress going on this? I added your email to package.json and bower.json

**Comment by craigsketchley** [comment]
Yeah, done. Just struggling to test it.

**Comment by rwwagner90** [comment]
@craigsketchley anything I can do to help? Just to note, I changed all of our tests to run in Chrome because there is currently a bug with Ember that breaks if vendor.js is too big with Phantom.

**Comment by rwwagner90** [comment]
Merged the PR in @craigsketchley, so I am closing this.
